### ISSUE TITLE
Add support for custom vias

### ISSUE THREAD

**Issue by nickson-jose** [HanyMoussa/SPEF_EXTRACTOR#1]
Hi I'm facing below error while generating spef file from the above SPEF_EXTRACTOR..attaching the lef and def file for reference too..
[lef_def.tar.gz](https://github.com/HanyMoussa/SPEF_EXTRACTOR/files/5258784/lef_def.tar.gz)

```
Start parsing LEF file...
Parsing LEF file done.
Start parsing DEF file...
Parsing DEF file done.
Parameters Used:
Edge Capacitance Factor: 1
Wire model: PI
Traceback (most recent call last):
  File "main.py", line 482, in <module>
    firstLayer = lef_parser.via_dict[myVia].layers[0]
KeyError: 'via2_FR'
```

**Comment by HanyMoussa** [comment]
Looking at the provided def and lef files, via2_FR, and other vias, are used in the def file but their definitions do not exist in the lef file. All such vias must have corresponding definitions in the lef file. To give an illustration, via2_FR should have a definition in the lef file looking like:
```
VIA via2_FR 
 LAYER met2 ;
 RECT -0.14 -0.185 0.14 0.185 ;
 LAYER via2 ;
 RECT -0.1 -0.1 0.1 0.1 ; 
 LAYER met3 ;
 RECT -0.165 -0.165 0.165 0.165 ;
 END via2_FR
```

**Comment by agorararmard** [comment]
@HanyMoussa I was about to open the same issue. This error is because the used lef/def parser doesn't support custom vias, which are created by TritonRoute and so most of the users will face this eventually. Custom vias are defined in the def file. i.e. in the attached test case for via2_FR the definition is:
```
- via2_FR 
+ RECT met2 ( -140 -185 ) ( 140 185 ) 
+ RECT via2 ( -100 -100 ) ( 100 100 ) 
+ RECT met3 ( -165 -165 ) ( 165 165 ) 
 
 ;
``` 
One solution would be to modify the parser itself. Another is to extract the info from the parser and add it to the LEF file in the format you mentioned above prior to passing the lef/def to the parser.

This is blocking the integration with OpenLANE. So, please, resolve this at your earliest convenience. 

[spm_testcase.tar.gz](https://github.com/HanyMoussa/SPEF_EXTRACTOR/files/5262812/spm_testcase.tar.gz)

**Comment by ramezmoussa** [comment]
@nickson-jose @agorararmard  support for custom vias has been added and it should solve this issue.
